### ISSUE TITLE
想请教一下这个怎么解决啊

### ISSUE THREAD

**Issue by FoneG** [adow/Dollarss#3]
<img width="773" alt="2016-11-29 2 31 29" src="https://cloud.githubusercontent.com/assets/15395364/20699113/8eaeaa52-b640-11e6-9fcf-54423b17a6d9.png">

**Comment by leoSince2017** [comment]
我把这句话注掉了，于是编译通过并且在模拟器上启动了。但是我只进入了开始界面而已，没登录进去。
<img width="318" alt="2017-08-17 11 29 30" src="https://user-images.githubusercontent.com/30584485/29394830-9663bf86-833f-11e7-9204-d09a45e2481e.png">
